cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

luckyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import registration_view, login_view, logout_view
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('manager/', include('manager.urls', namespace='manager'))
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import OrderListView, close_order_view

app_name = 'manager'

urlpatterns = [
    path('orders/', OrderListView.as_view(), name='orders'),
    path('orders/update/<int:order_pk>', close_order_view, name='close_order')
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect
from django.utils.decorators import method_decorator

from order.models import Order
from django.core.paginator import Paginator
from django.views.generic import ListView


def is_manager(user):
    return user.groups.filter(name='manager').exists()


@method_decorator(login_required(login_url='/login/'), name='dispatch')
@method_decorator(user_passes_test(is_manager), name='dispatch')
class OrderListView(ListView):
    template_name = 'order_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        return Order.objects.filter(paid=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        paginator = Paginator(self.get_queryset(), 9)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = super().get_context_data(**kwargs)
        context['page_obj'] = page_obj
        return context


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def close_order_view(request, order_pk):
    Order.objects.filter(pk=order_pk).update(paid=False)
    return redirect('manager:orders')

manager/templates/order_list.html
{% extends 'base_shop.html' %}
{% load static %}
{% load manager_tags %}

{% block title %}Список заказів{% endblock %}

{% block content %}
    <section class="mt-0">
    <div class="container-fluid">
     <!-- Category Top Banner -->
        <div class="py-10 bg-img-cover bg-overlay-dark position-relative overflow-hidden bg-pos-center-center rounded-0"
             style="background-image: url({% static 'images/banners/banner-category-top.jpg' %});">
            <div class="container-fluid position-relative z-index-20" data-aos="fade-right" data-aos-delay="300">
                <h1 class="fw-bold display-6 mb-4 text-white">Cписок замовлень</h1>
                <h1 class="fw-bold display-6 mb-4 text-white"></h1>
                <div class="col-12 col-md-6">
                    <p class="text-white mb-0 fs-5">
                    </p>
                </div>
            </div>
        </div>
        <!-- Category Top Banner -->
        <div class="accordion mt-3" id="accordionExample">
    {% for order in page_obj.object_list %}
  <div class="accordion-item">
    <h2 class="accordion-header" id="heading{{ forloop.counter|accordition_id }}">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter|accordition_id }}" aria-expanded="true" aria-controls="collapse{{ forloop.counter|accordition_id }}">
        Замовлення №{{ order.id }}: {{ order.name }}, {{ order.email }}, {{ order.phone }}
      </button>
    </h2>
    <div id="collapse{{ forloop.counter|accordition_id }}" class="accordion-collapse collapse show" aria-labelledby="heading{{ forloop.counter|accordition_id }}" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          <p>
              Спосіб доставки: {{ order.delivery }}
          </p>
          <p>
              Країна {{ order.country }}
          </p>
          <p>
              Місто: {{ order.city }}
          </p>
          <p>
              Адреса: {{ order.address }}
          </p>
          <p>
              Спосіб оплати: {{ order.payment }}
          </p>
          <p>Продукти:</p>
      <div class="row">
      {% for item in order.items.all %}
          <div class="col-sm-2">
              <div class="card" style="width: 18rem;">
              <img src="{{ item.product.image.url }}" class="card-img-top">
              <div class="card-body">
                <p class="card-text">{{ item.product.name }}</p>
                  <p class="card-text">Ціна: {{ item.product.price }}</p>
                  <p class="card-text">Розмір: {{ item.size }}</p>
                  <p class="card-text">Кількість: {{ item.count }}</p>
              </div>
            </div>
          </div>
      {% endfor %}
      </div>

      </div>
        <h2>До сплати: {{ order.get_total_cost }}</h2>
         <a href="{% url 'manager:close_order' order_pk=order.pk %}" class="btn btn-primary">Закрити замовлення</a>
    </div>
  </div>
    {% endfor %}
</div>
    </div>
    </section>
{% endblock %}