cart/urls.py
from django.urls import path
from .views import cart_detail, cart_add, cart_remove

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>', cart_remove, name='cart_remove'),
]

luckyshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from account.views import registration_view, login_view, logout_view
import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('registration/', registration_view, name='registration'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('manager/', include('manager.urls', namespace='manager'))
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import create_order

app_name = 'order'

urlpatterns = [
    path('create/', create_order, name='create_order')
]

shop/urls.py
from django.urls import path, include
from shop.views import HomepageView, ProductsListView, SearchProductsView, ProductDetailView

app_name = "shop"

shop_urls = [
    path('<slug:slug_category>', ProductsListView.as_view(), name='category_products_view'),
    path('type-clothes/<slug:slug_type_clothes>', ProductsListView.as_view(), name='products_type_clothes_view'),
    path('<slug:slug_category>/special-offer', ProductsListView.as_view(special=True),
         name='products_category_special_view'),
    path('<slug:slug_category>/novelties', ProductsListView.as_view(new_in=True),
         name='novelties_products_category_view'),
    path('<slug:slug_category>/<slug:slug_catalog>', ProductsListView.as_view(),
         name='products_category_catalog_view'),
    path('<slug:slug_category>/<slug:slug_catalog>/special-offer', ProductsListView.as_view(special=True),
         name='products_category_catalog_special_view'),
    path('<slug:slug_category>/<slug:slug_catalog>/<slug:slug_type_clothes>', ProductsListView.as_view(),
         name='products_category_type_clothes_view'),
]

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),

    path('search', SearchProductsView.as_view(), name='search_product'),
    path('special-offer', ProductsListView.as_view(special=True), name='special_products_view'),
    path('novelties', ProductsListView.as_view(new_in=True), name='novelties_products_view'),
    path('shop/', include(shop_urls)),
    path('product/<slug:slug_product>', ProductDetailView.as_view(), name='product')
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from shop.models import Product
from django.views.decorators.http import require_GET


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart.html', {'cart': cart})


@require_GET
def cart_add(request, product_id):
    size = request.GET.get('size')
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product, size, 1, False)
    if request.GET.get('add_cart'):
        return redirect('shop:category_products_view', slug_category=product.category.slug)
    elif request.GET.get('add_to_buy'):
        return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/base_cart.html
{% extends 'base.html' %}

{% block main %}
    {% block content %}
    {% endblock %}
{% endblock %}

cart/templates/cart.html
{% extends 'base_cart.html' %}
{% load static %}

{% block title %}
    Кошик
{% endblock %}

{% block content %}
    <!-- Main Section-->
    <section class="mt-0 overflow-lg-hidden  vh-lg-100">
        <!-- Page Content Goes Here -->
        <div class="container">
            <div class="row g-0 vh-lg-100">
                <div class="col-12 col-lg-7 pt-5 pt-lg-10">
                    <div class="pe-lg-5">
                        <!-- Logo-->
                        <a class="navbar-brand fw-bold fs-3 flex-shrink-0 mx-0 px-0" href="{% url 'shop:homepage' %}">
                            <div class="d-flex align-items-center">
                                <svg class="f-w-7" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 77.53 72.26">
                                    <path d="M10.43,54.2h0L0,36.13,10.43,18.06,20.86,0H41.72L10.43,54.2Zm67.1-7.83L73,54.2,68.49,62,45,48.47,31.29,72.26H20.86l-5.22-9L52.15,0H62.58l5.21,9L54.06,32.82,77.53,46.37Z" fill="currentColor" fill-rule="evenodd"/>
                                </svg>
                            </div>
                        </a>
                        <!-- / Logo-->
                        <div class="mt-5">
                            <h3 class="fs-5 fw-bolder mb-0 border-bottom pb-4">Ваш кошик</h3>
                            <div class="table-responsive">
                                <table class="table align-middle">
                                    <tbody class="border-0">
                                        <!-- Cart Item-->
                                        {% for item in cart %}
                                            {% with product=item.product %}
                                        <div class="row mx-0 py-4 g-0 border-bottom">
                                            <div class="col-2 position-relative">
                                                <picture class="d-block border">
                                                    <img class="img-fluid" src="{{ product.image.url }}">
                                                </picture>
                                            </div>
                                            <div class="col-9 offset-1">
                                                <div>
                                                    <h6 class="justify-content-between d-flex align-items-start mb-2">
                                                        <a href="{% url 'shop:product' slug_product=product.slug %}" class="text-decoration-none">{{ product.name }}</a>
                                                        <a href="{% url 'cart:cart_remove' product_id=product.id %}" class="text-decoration-none"><i class="ri-close-line ms-3"></i></a>
                                                    </h6>
                                                    <span class="d-block text-muted fw-bolder text-uppercase fs-9">Розмір: {{ item.size }} / К-сть: {{ item.count }}</span>
                                                </div>
                                                <p class="fw-bolder text-end text-muted m-0">{{ product.price }}</p>
                                            </div>
                                        </div>
                                            {% endwith %}
                                        {% endfor %}
                                        <!-- / Cart Item-->
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-5 bg-light pt-lg-10 aside-checkout pb-5 pb-lg-0 my-5 my-lg-0">
                    <div class="p-4 py-lg-0 pe-lg-0 ps-lg-5">
                        <div class="pb-4 border-bottom">
                            <div class="d-flex flex-column flex-md-row justify-content-md-between mb-4 mb-md-2">
                                <div>
                                    <p class="m-0 fw-bold fs-5">До сплати:</p>
                                </div>
                                <p class="m-0 fs-5 fw-bold">{{ cart.get_total_price|floatformat:2 }} грн</p>
                            </div>
                        </div>
                        <a href="{% url 'order:create_order' %}" class="btn btn-dark w-100 text-center" role="button">Перейти до сплати</a>
                        <a href="{% url 'shop:homepage' %}" class="btn btn-outline-dark w-100 text-center mt-3" role="button">Продовжити покупки</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /Page Content -->
    </section>
    <!-- / Main Section-->
{% endblock %}